config/routes.rb
Rails.application.routes.draw do

  root 'visitantes#index'

  resources :visitantes
  resources :profissionals
  resources :setors
  resources :unidades
  devise_for :users

devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/unidade.rb
class Unidade < ApplicationRecord
end

app/controllers/unidades_controller.rb
class UnidadesController < ApplicationController
  before_action :set_unidade, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /unidades or /unidades.json
  def index
    @unidades = Unidade.all
  end

  # GET /unidades/1 or /unidades/1.json
  def show
  end

  # GET /unidades/new
  def new
    @unidade = Unidade.new
  end

  # GET /unidades/1/edit
  def edit
  end

  # POST /unidades or /unidades.json
  def create
    @unidade = Unidade.new(unidade_params)

    respond_to do |format|
      if @unidade.save
        format.html { redirect_to unidade_url(@unidade), notice: "Unidade was successfully created." }
        format.json { render :show, status: :created, location: @unidade }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @unidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /unidades/1 or /unidades/1.json
  def update
    respond_to do |format|
      if @unidade.update(unidade_params)
        format.html { redirect_to unidade_url(@unidade), notice: "Unidade was successfully updated." }
        format.json { render :show, status: :ok, location: @unidade }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @unidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unidades/1 or /unidades/1.json
  def destroy
    @unidade.destroy!

    respond_to do |format|
      format.html { redirect_to unidades_url, notice: "Unidade was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unidade
      @unidade = Unidade.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def unidade_params
      params.require(:unidade).permit(:nome, :endereco)
    end
end

app/helpers/unidades_helper.rb
module UnidadesHelper
end

app/views/unidades/_form.html.erb
<%= simple_form_for(@unidade) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :nome %>
    <%= f.input :endereco %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/unidades/_unidade.html.erb
<div id="<%= dom_id unidade %>">
  <p>
    <strong>Nome:</strong>
    <%= unidade.nome %>
  </p>

  <p>
    <strong>Endereco:</strong>
    <%= unidade.endereco %>
  </p>

</div>

app/views/unidades/edit.html.erb
<h1>Editing unidade</h1>

<%= render "form", unidade: @unidade %>

<br>

<div>
  <%= link_to "Ver", @unidade %> |
  <%= link_to "Voltar", unidades_path %>
</div>

app/views/unidades/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Unidades</h1>

<div id="unidades">
  <% @unidades.each do |unidade| %>
    <%= render unidade %>
    <p>
      <%= link_to "Ver", unidade %>
    </p>
  <% end %>
</div>

<%= link_to "Nova unidade", new_unidade_path %>
<%= link_to "Voltar", visitantes_path %></br>

app/views/unidades/new.html.erb
<h1>New unidade</h1>

<%= render "form", unidade: @unidade %>

<br>

<div>
  <%= link_to "Voltar", unidades_path %>
</div>

app/views/unidades/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @unidade %>

<div>
  <%= link_to "Edit this unidade", edit_unidade_path(@unidade) %> |
  <%= link_to "Back to unidades", unidades_path %>

  <%= button_to "Destroy this unidade", @unidade, method: :delete %>
</div>