config/routes.rb
Rails.application.routes.draw do

  root 'visitantes#index'

  resources :visitantes
  resources :profissionals
  resources :setors
  resources :unidades
  devise_for :users

devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/setor.rb
class Setor < ApplicationRecord
  has_many :colaboradors
  belongs_to :unidade
end

app/controllers/setors_controller.rb
class SetorsController < ApplicationController
  before_action :set_setor, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /setors or /setors.json
  def index
    @setors = Setor.all
  end

  # GET /setors/1 or /setors/1.json
  def show
  end

  # GET /setors/new
  def new
    @setor = Setor.new
  end

  # GET /setors/1/edit
  def edit
  end

  # POST /setors or /setors.json
  def create
    @setor = Setor.new(setor_params)

    respond_to do |format|
      if @setor.save
        format.html { redirect_to setor_url(@setor), notice: "Setor was successfully created." }
        format.json { render :show, status: :created, location: @setor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @setor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /setors/1 or /setors/1.json
  def update
    respond_to do |format|
      if @setor.update(setor_params)
        format.html { redirect_to setor_url(@setor), notice: "Setor was successfully updated." }
        format.json { render :show, status: :ok, location: @setor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @setor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /setors/1 or /setors/1.json
  def destroy
    @setor.destroy!

    respond_to do |format|
      format.html { redirect_to setors_url, notice: "Setor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setor
      @setor = Setor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def setor_params
      params.require(:setor).permit(:nome, :unidade_id)
    end
end

app/helpers/setors_helper.rb
module SetorsHelper
end

app/views/setors/_form.html.erb
<%= simple_form_for(@setor) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :nome %>
    <%= f.association :unidade %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/setors/_setor.html.erb
<div id="<%= dom_id setor %>">
  <p>
    <strong>Nome:</strong>
    <%= setor.nome %>
  </p>

  <p>
    <strong>Unidade:</strong>
    <%= setor.unidade_id %>
  </p>

</div>

app/views/setors/edit.html.erb
<h1>Editing setor</h1>

<%= render "form", setor: @setor %>

<br>

<div>
  <%= link_to "Ver", @setor %> |
  <%= link_to "Voltar", setors_path %>
</div>

app/views/setors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Setors</h1>

<div id="setors">
  <% @setors.each do |setor| %>
    <%= render setor %>
    <p>
      <%= link_to "Ver", setor %>
    </p>
  <% end %>
</div>

<%= link_to "Novo Setor", new_setor_path %>
<%= link_to "Voltar", visitantes_path %></br>

app/views/setors/new.html.erb
<h1>New setor</h1>

<%= render "form", setor: @setor %>

<br>

<div>
  <%= link_to "Voltar", setors_path %>
</div>

app/views/setors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @setor %>

<div>
  <%= link_to "Editar setor", edit_setor_path(@setor) %> |
  <%= link_to "Voltar", setors_path %>

  <%= button_to "Apagar esse setor", @setor, method: :delete %>
</div>