config/routes.rb
Rails.application.routes.draw do

  root 'visitantes#index'

  resources :visitantes
  resources :profissionals
  resources :setors
  resources :unidades
  devise_for :users

devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/profissional.rb
class Profissional < ApplicationRecord
  belongs_to :setor
end

app/controllers/profissionals_controller.rb
class ProfissionalsController < ApplicationController
  before_action :set_profissional, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /profissionals or /profissionals.json
  def index
    @profissionals = Profissional.all
  end

  # GET /profissionals/1 or /profissionals/1.json
  def show
  end

  # GET /profissionals/new
  def new
    @profissional = Profissional.new
  end

  # GET /profissionals/1/edit
  def edit
  end

  # POST /profissionals or /profissionals.json
  def create
    @profissional = Profissional.new(profissional_params)

    respond_to do |format|
      if @profissional.save
        format.html { redirect_to profissional_url(@profissional), notice: "Profissional was successfully created." }
        format.json { render :show, status: :created, location: @profissional }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @profissional.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profissionals/1 or /profissionals/1.json
  def update
    respond_to do |format|
      if @profissional.update(profissional_params)
        format.html { redirect_to profissional_url(@profissional), notice: "Profissional was successfully updated." }
        format.json { render :show, status: :ok, location: @profissional }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profissional.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profissionals/1 or /profissionals/1.json
  def destroy
    @profissional.destroy!

    respond_to do |format|
      format.html { redirect_to profissionals_url, notice: "Profissional was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profissional
      @profissional = Profissional.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def profissional_params
      params.require(:profissional).permit(:nome, :setor_id)
    end
end

app/helpers/profissionals_helper.rb
module ProfissionalsHelper
end

app/views/profissionals/_form.html.erb
<%= simple_form_for(@profissional) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :nome %>
    <%= f.association :setor %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/profissionals/_profissional.html.erb
<div id="<%= dom_id profissional %>">
  <p>
    <strong>Nome:</strong>
    <%= profissional.nome %>
  </p>

  <p>
    <strong>Setor:</strong>
    <%= profissional.setor_id %>
  </p>

</div>

app/views/profissionals/edit.html.erb
<h1>Editing profissional</h1>

<%= render "form", profissional: @profissional %>

<br>

<div>
  <%= link_to "Show this profissional", @profissional %> |
  <%= link_to "Back to profissionals", profissionals_path %>
</div>

app/views/profissionals/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Colaboradores</h1>

<div id="profissionals">
  <% @profissionals.each do |profissional| %>
    <%= render profissional %>
    <p>
      <%= link_to "Ver colaborador", profissional %>
    </p>
  <% end %>
</div>

<%= link_to "Novo Colaborador", new_profissional_path %>
<%= link_to "Voltar", visitantes_path %></br>

app/views/profissionals/new.html.erb
<h1>New profissional</h1>

<%= render "form", profissional: @profissional %>

<br>

<div>
  <%= link_to "Back to profissionals", profissionals_path %>
</div>

app/views/profissionals/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @profissional %>

<div>
  <%= link_to "Edit this profissional", edit_profissional_path(@profissional) %> |
  <%= link_to "Back to profissionals", profissionals_path %>

  <%= button_to "Destroy this profissional", @profissional, method: :delete %>
</div>