config/routes.rb
Rails.application.routes.draw do

  root 'visitantes#index'

  resources :visitantes
  resources :profissionals
  resources :setors
  resources :unidades
  devise_for :users

devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/visitante.rb
class Visitante < ApplicationRecord
  belongs_to :setor

  scope :search, ->(query) { where("cpf like ?", "%#{query}%")}
end

app/controllers/visitantes_controller.rb
class VisitantesController < ApplicationController
  before_action :set_visitante, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /visitantes or /visitantes.json
  def index
    if params[:search]
      @visitantes = Visitante.search(params[:search])
    else
     @visitantes = Visitante.all
  end
end

  # GET /visitantes/1 or /visitantes/1.json
  def show
  end

  # GET /visitantes/new
  def new
    @visitante = Visitante.new
  end

  # GET /visitantes/1/edit
  def edit
  end

  # POST /visitantes or /visitantes.json
  def create
    @visitante = Visitante.new(visitante_params)

    respond_to do |format|
      if @visitante.save
        format.html { redirect_to visitante_url(@visitante), notice: "Visitante was successfully created." }
        format.json { render :show, status: :created, location: @visitante }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @visitante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visitantes/1 or /visitantes/1.json
  def update
    respond_to do |format|
      if @visitante.update(visitante_params)
        format.html { redirect_to visitante_url(@visitante), notice: "Visitante was successfully updated." }
        format.json { render :show, status: :ok, location: @visitante }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @visitante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visitantes/1 or /visitantes/1.json
  def destroy
    @visitante.destroy!

    respond_to do |format|
      format.html { redirect_to visitantes_url, notice: "Visitante was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visitante
      @visitante = Visitante.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def visitante_params
      params.require(:visitante).permit(:nome, :cpf, :rg, :tel, :data_hora, :concluida, :foto, :setor_id)
    end
end

app/helpers/visitantes_helper.rb
module VisitantesHelper
end

app/views/visitantes/_form.html.erb
<%= simple_form_for(@visitante) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :nome %>
    <%= f.input :cpf %>
    <%= f.input :rg %>
    <%= f.input :tel %>
    <%= f.input :data_hora %>
    <%= f.input :concluida %>
    <%= f.input :foto %>
    <%= f.association :setor %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/visitantes/_visitante.html.erb
<div id="<%= dom_id visitante %>">
  <p>
    <strong>Nome:</strong>
    <%= visitante.nome %>
  </p>

  <p>
    <strong>Cpf:</strong>
    <%= visitante.cpf %>
  </p>

  <p>
    <strong>Rg:</strong>
    <%= visitante.rg %>
  </p>

  <p>
    <strong>Tel:</strong>
    <%= visitante.tel %>
  </p>

  <p>
    <strong>Data hora:</strong>
    <%= visitante.data_hora %>
  </p>

  <p>
    <strong>Concluida:</strong>
    <%= visitante.concluida %>
  </p>

  <p>
    <strong>Foto:</strong>
    <%= visitante.foto %>
  </p>

  <p>
    <strong>Setor:</strong>
    <%= visitante.setor_id %>
  </p>

</div>

app/views/visitantes/edit.html.erb
<h1>Editing visitante</h1>

<%= render "form", visitante: @visitante %>

<br>

<div>
  <%= link_to "Ver", @visitante %> |
  <%= link_to "Voltar", visitantes_path %>
</div>

app/views/visitantes/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Visitantes</h1>
<li><%= current_user.email =%></li>

<% if can? :read, Visitante %>

<%= form_tag(visitantes_path, :method => :get) do %>
  <%= text_field_tag 'search', nil, placeholder: 'Digite o CPF do visitante' %>
  <%= submit_tag "Buscar" %>  
    
    <% end %>

<div id="visitantes">
  <% @visitantes.each do |visitante| %>
    <%= render visitante %>
    <p>
      <%= link_to "Visualizar visitantes", visitante %>
    </p>
  <% end %>
</div>
<% end %>

<% if can? :create, Visitante %>
<%= link_to "Cadastrar visitante", new_visitante_path %></br>


<% end %>
  <% if can? :create, Unidade %>
  <%= link_to "Cadastrar Unidade", new_unidade_path %></br>
  <%= link_to "Cadastrar Setor", new_setor_path %></br>
  <%= link_to "Cadastrar Colaborador", new_profissional_path %></br>
  <%= button_to "Criar novo usuário", 'new_user_registration_path', method: :new %>
<% end %>


<%= link_to "Sair",  destroy_user_session_path, method: :destroy %>

app/views/visitantes/new.html.erb
<h1>New visitante</h1>

<%= render "form", visitante: @visitante %>

<br>

<div>
  <%= link_to "Back to visitantes", visitantes_path %>
</div>

app/views/visitantes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @visitante %>

<div>
  <%= link_to "Edit this visitante", edit_visitante_path(@visitante) %> |
  <%= link_to "Back to visitantes", visitantes_path %>

  <%= button_to "Destroy this visitante", @visitante, method: :delete %>
</div>